# Generated by Django 3.2 on 2021-04-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='surveyquestionalternative',
            name='question_alternative',
            field=models.CharField(max_length=150),
        ),
    ]
